// The JavaScript half of the validator parity check.
//
// studio/tests/fixtures/parity.json is generated by
// `python3 -m datamaps.studio --write-fixture`: a corpus of documents (a
// synthetic technology and catalog, then one breakage at a time on top of
// each) and, for every one, the messages schema.py produces against the
// reduced fixture schema.  tests/test_studio_parity.py fails when that file
// is stale; this test fails when validate.js does not say the same things
// in the same order.  Together they prove the port without Python and
// Node ever sharing a machine - CI runs each on its own image.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SCHEMA } from "./fixtures.js";
import { validateCatalog, validateTechnology } from "../lib/validate.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PARITY = JSON.parse(
  readFileSync(path.join(HERE, "fixtures", "parity.json"), "utf8"));

function messages(item) {
  const issues = item.kind === "catalog"
    ? validateCatalog(item.doc, SCHEMA)
    : validateTechnology(item.doc, item.id, SCHEMA);
  return issues.map((issue) => issue.message);
}

test("the fixture is well formed", () => {
  assert.deepEqual(Object.keys(PARITY).sort(), ["cases", "expected"]);
  assert.equal(PARITY.cases.length, PARITY.expected.length);
  assert.ok(PARITY.cases.length > 50);
  const labels = PARITY.cases.map((item) => item.label);
  assert.equal(new Set(labels).size, labels.length);
  assert.ok(labels.includes("base/technology"));
  assert.ok(labels.includes("base/catalog"));
});

test("every case produces the same messages in the same order as schema.py", () => {
  PARITY.cases.forEach((item, index) => {
    assert.deepEqual(messages(item), PARITY.expected[index], item.label);
  });
});

test("the base documents are valid to both sides", () => {
  for (const item of PARITY.cases) {
    if (item.label.startsWith("base/")) {
      assert.deepEqual(messages(item), []);
    }
  }
});
